version: '3'
services:
  backend:
    build: 
      context: .
    links:
      - 'db'
    environment:
      - MODE=PRODUCTION
    ports:
      - '9000:9000'
    networks:
      - server-network
  db:
    image: "mongo:3.6"
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'      
    networks:
      - server-network
networks:
  server-network:
    driver: bridge
volumes:
  node_modules:
    driver: local
  mongodb-data:
    driver: local